sudo: false
dist: xenial
cache: pip
language: python
python:
    - "3.6"

install:
    - pip install --upgrade pip setuptools wheel
    - pip install -q -r dev-requirements.txt
    - pip install -q -r requirements.txt --only-binary=numpy,scipy
script:
    - flake8 geomstats
    - nose2 --with-coverage --verbose
env:
    - GEOMSTATS_BACKEND=numpy
    - GEOMSTATS_BACKEND=pytorch

after_success:
    - bash <(curl -s https://codecov.io/bash) -c -F $GEOMSTATS_BACKEND
