sudo: false
dist: xenial
cache: pip
language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install --upgrade "pip<20.0" setuptools wheel
    - pip install -q -r dev-requirements.txt
    - pip install -q -r requirements.txt --only-binary=numpy,scipy
script:
    - >
      flake8 $(git diff --name-only master HEAD geomstats examples tests)
      --ignore=D
    - flake8 geomstats/geometry
    - |
      if [[ $TRAVIS_PYTHON_VERSION != 3.8 ||
            ($TRAVIS_PYTHON_VERSION == 3.8 &&
             $GEOMSTATS_BACKEND != tensorflow) ]]; then
        nose2 --with-coverage --verbose tests
      fi
env:
    - GEOMSTATS_BACKEND=numpy
    - GEOMSTATS_BACKEND=pytorch
    - GEOMSTATS_BACKEND=tensorflow

after_success:
    - bash <(curl -s https://codecov.io/bash) -c -F $GEOMSTATS_BACKEND
