sudo: false
dist: trusty
cache: pip
language: python
python:
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"

install:
    - pip install --upgrade pip setuptools wheel
    - pip install -q -r requirements.txt --only-binary=numpy,scipy
script:
    - flake8 geomstats
    - nose2 --with-coverage --verbose
env:
    - GEOMSTATS_BACKEND=numpy
    - GEOMSTATS_BACKEND=pytorch
    - GEOMSTATS_BACKEND=tensorflow

after_success:
    - bash <(curl -s https://codecov.io/bash) -c -F $GEOMSTATS_BACKEND
