name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hello, ${{ github.actor }} ðŸ‘‹
          Welcome to Geomstats! Thank you and congratulations for opening your first issue for this project! ðŸŽ‰ 
          Please do check out our [Contributing Guidelines](https://geomstats.github.io/contributing.html).
          Incase you want to claim this issue, please comment down below! One of our maintainers will be here shortly.
          Feel free to join us on [Slack](https://join.slack.com/t/geomstats/shared_invite/zt-15t8k0q7r-Duxt6j6aA3rDOIms2Vd~RQ) by dropping an email [here](mailto:ninamiolane@ucsb.edu).
        pr-message: |
          Hello, ${{ github.actor }} ðŸ‘‹
          Welcome to Geomstats! Thank you and congratulations for opening your first PR for this project! ðŸŽ‰
          One of our maintainers will be here shortly.
          We recommend that you check out our [Contributing Guidelines](https://geomstats.github.io/contributing.html) to avoid tests from failing and to make sure the necessary is followed.
          Let our maintainers know if you need any help! Feel free to join us on [Slack](https://join.slack.com/t/geomstats/shared_invite/zt-15t8k0q7r-Duxt6j6aA3rDOIms2Vd~RQ) by dropping an email [here](mailto:ninamiolane@ucsb.edu).