name: "Testing"

on:
  push:
    branches: [master, github-actions-test]
    paths-ignore:
      - "docs/**"
      - "README.rst"
      - "LICENSE.md"
      - ".github/workflows/docs.yml"
      - ".deepsource.toml"
      - ".gitignore"

  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "README.rst"
      - ".github/workflows/docs.yml"
      - "LICENSE.md"
      - ".deepsource.toml"
      - ".gitignore"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
        geomstats-backend: ["autograd", "numpy", "pytorch"]
        test-folder: ["tests/tests_geomstats/", "tests/tests_scripts"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Build using Python ${{matrix.python-version}} and Backend ${{matrix.geomstats-backend}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: install dependencies [pip]
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e .[opt,test,${{ matrix.geomstats-backend }}]

      - name: Add annotations [pytest]
        run: pip install pytest-github-actions-annotate-failures

      - name: unit testing [pytest]
        env:
          GEOMSTATS_BACKEND: ${{matrix.geomstats-backend}}
        run: |
          pytest --cov-report term --cov=geomstats ${{matrix.test-folder}}

      - name: uploading code coverage [codecov]
        if: ${{matrix.python-version == 3.8 && matrix.test-folder == 'tests/tests_geomstats/'}}
        run: |
          bash <(curl -s https://codecov.io/bash) -c -F ${{matrix.geomstats-backend}}
