name: "Testing"

on:
  push:
    branches: [main, github-actions-test]
    paths-ignore:
      - "docs/**"
      - "README.rst"
      - "LICENSE.md"
      - ".github/workflows/docs.yml"
      - ".deepsource.toml"
      - ".gitignore"

  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "README.rst"
      - ".github/workflows/docs.yml"
      - "LICENSE.md"
      - ".deepsource.toml"
      - ".gitignore"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]
        geomstats-backend: ["autograd", "numpy", "pytorch"]
        test-folder: ["tests/tests_geomstats/", "tests/tests_scripts"]
      fail-fast: false
    env:
      GEOMSTATS_BACKEND: ${{matrix.geomstats-backend}}

    steps:
      - uses: actions/checkout@v4
      - name: Build using Python ${{matrix.python-version}} and Backend ${{matrix.geomstats-backend}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{matrix.geomstats-backend}}-${{matrix.os}}-${{matrix.python-version}}-${{ hashFiles('pyproject.toml') }}

      - name: install dependencies [pip]
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e .[opt,test,test-scripts,${{ matrix.geomstats-backend }}]

      - name: Add annotations [pytest]
        run: pip install pytest-github-actions-annotate-failures

      - name: unit testing for geomstats [pytest]
        if: ${{matrix.test-folder == 'tests/tests_geomstats/'}}
        run: |
          pytest --cov-report term -m "not (slow or redundant)" --cov=geomstats ${{matrix.test-folder}}

      - name: unit testing for geomstats (slow) [pytest]
        if: ${{matrix.test-folder == 'tests/tests_geomstats/'}}
        run: |
          pytest --cov-report term -m "slow and (not redundant)" --cov-append --cov=geomstats ${{matrix.test-folder}}

      - name: unit testing for scripts [pytest]
        if: ${{matrix.test-folder == 'tests/tests_scripts'}}
        run: |
          pytest ${{matrix.test-folder}}

      - name: uploading code coverage [codecov]
        if: ${{matrix.python-version == 3.11 && matrix.test-folder == 'tests/tests_geomstats/'}}
        run: |
          bash <(curl -s https://codecov.io/bash) -c -F ${{matrix.geomstats-backend}}
